In [29]:
from tensorflow.keras.preprocessing.text import one_hot


In [30]:
## sentences
sent = [
    "The glass of milk",
    "The glass of juice",
    "hey i went there again",
    "I love playing cricket",
    "Do you think its good ?"
]

In [31]:
vocab_size = 10000

In [32]:
one_hot_repr = [one_hot(line,vocabulary_size) for line in sent]

In [33]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [34]:
import numpy as np
import pandas as pd

In [35]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding="pre",maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7009 1544 6983  639]
 [   0    0    0    0 7009 1544 6983 3256]
 [   0    0    0 5862 6072 3147 6076 2297]
 [   0    0    0    0 6072 3672 2009 6779]
 [   0    0    0 5965 5368 6574 4518 2367]]


In [36]:
dim=10

In [37]:
from tensorflow.keras.layers import Flatten,Dense

In [42]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size,output_dim=dim,input_length=sent_length))
model.compile("adam","mse")

In [43]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 383ms/step


array([[[-0.0321364 ,  0.00057731, -0.01805557, -0.04920933,
          0.01568611,  0.03373951,  0.02451613, -0.00145912,
         -0.00233524,  0.02100506],
        [-0.0321364 ,  0.00057731, -0.01805557, -0.04920933,
          0.01568611,  0.03373951,  0.02451613, -0.00145912,
         -0.00233524,  0.02100506],
        [-0.0321364 ,  0.00057731, -0.01805557, -0.04920933,
          0.01568611,  0.03373951,  0.02451613, -0.00145912,
         -0.00233524,  0.02100506],
        [-0.0321364 ,  0.00057731, -0.01805557, -0.04920933,
          0.01568611,  0.03373951,  0.02451613, -0.00145912,
         -0.00233524,  0.02100506],
        [ 0.0092526 , -0.02192874, -0.01194192, -0.01793882,
         -0.01114221, -0.0404622 , -0.00890472, -0.03697114,
         -0.0021126 , -0.01113747],
        [-0.01017231,  0.02656339, -0.0053785 ,  0.01485676,
         -0.04628811, -0.02943697,  0.01910118, -0.03695666,
         -0.049348  ,  0.03282143],
        [ 0.02089446, -0.01787109,  0.02537313, -0.0